"""
@file_name: message_bus_module.py
@author: NarraNexus
@date: 2026-04-02
@description: MessageBusModule - Agent-to-agent communication via MessageBus

Protocol-agnostic message bus for agent-to-agent communication. Provides MCP
tools for sending/receiving messages, managing channels, and discovering agents.

Instance level: Agent-level (one per Agent, is_public=True).

Behavior design:
- Reply Discipline: prevent infinite trigger loops between agents
- Selective mark_read: messages the agent ignores stay unread (resurface next turn)
- Context caps: unread/channels/known_agents all bounded to prevent pollution
- Source recognition: incoming bus messages are prefixed with [MessageBus · ...]
  so the agent can distinguish them from owner commands
"""

from __future__ import annotations

import json
from typing import Any, Optional

from loguru import logger

from xyz_agent_context.module.base import (
    XYZBaseModule,
    mcp_host,
    working_source_matches,
)
from xyz_agent_context.schema import (
    BUS_TEAM_ROOM_EXTRA_KEY,
    ModuleConfig,
    MCPServerConfig,
    ContextData,
    HookAfterExecutionParams,
    WorkingSource,
    is_agent_description_unset,
)
from xyz_agent_context.message_bus.system_messages import PLATFORM_MSG_TYPES
from xyz_agent_context.schema.team_schema import (
    TEAM_ROOM_OWNER_PREFIX,
    USER_SENDER_PREFIX,
)
from xyz_agent_context.settings import settings


# MCP server port for MessageBus tools
MESSAGE_BUS_MCP_PORT = 7820

# Context-injection caps to prevent pollution
MAX_UNREAD_IN_CONTEXT = 20
MAX_CHANNELS_IN_CONTEXT = 20
MAX_KNOWN_AGENTS_IN_CONTEXT = 50


#: What a platform line is called in the unread list. Matches the label
#: `message_bus_trigger._build_team_prompt` puts on the same rows.
SYSTEM_SENDER_LABEL = "[system]"


def _render_sender(from_agent: Any, msg_type: Any = None) -> str:
    """How a bus sender is named inside a `[MessageBus · … ]` tag.

    THREE kinds of sender reach this list, and only one of them is an agent.
    `schema/team_schema` defines both synthetic prefixes side by side, each
    marked "a non-agent sender":

    * ``usr_<user_id>`` — a PERSON. A team room carries its owner's own
      messages, and the raw id says nothing at all, least of all that the
      reader is looking at the person it works for.
    * ``team_<team_id>`` — the ROOM itself, i.e. the platform. Printing it
      verbatim invents a teammate the agent may then try to @mention back,
      which is exactly why `message_bus_trigger._who` refuses to.
    * anything else — a real agent.

    ``msg_type`` outranks the sender, and has to: a bulletin notice posted
    from the UI carries `msg_type=system_bulletin` but is stamped with the
    OWNER's ``usr_`` id (`team_bulletin.py`, no actor), so on the sender alone
    it reads as the owner speaking — and the Source-Recognition rules now say
    in as many words that a `User` sender is a person. Checking the type first
    is what stops the platform being quoted as the human.

    Named to match `message_bus_trigger._sender`, which renders the same rows
    the same way in the room's own prompt — one row, two surfaces, one name.
    """
    if (str(msg_type or "")) in PLATFORM_MSG_TYPES:
        return SYSTEM_SENDER_LABEL
    sender = str(from_agent or "unknown")
    if sender.startswith(TEAM_ROOM_OWNER_PREFIX):
        return SYSTEM_SENDER_LABEL
    if sender.startswith(USER_SENDER_PREFIX):
        return "User"
    return sender


def _bus_tag(from_agent: Any, channel_id: Any, msg_type: Any = None) -> str:
    """The `[MessageBus · sender · channel]` marker, built in exactly one place.

    The format had three copies — the worked example in the instructions and
    two render sites — and the example disagreed with both, showing a display
    name AND an id where the code emits a single sender field. That was
    survivable while the tag was decoration. It stopped being survivable when
    the rules started telling the agent to READ the sender out of it: an agent
    following a four-field example against a three-field tag looks for a name
    that is never there, and the field it finds in position two is the channel.

    So the example is generated by this same function, and the two can no
    longer drift apart. ``msg_type`` is optional precisely so the example stays
    constructible from two literals.
    """
    return f"[MessageBus · {_render_sender(from_agent, msg_type)} · {channel_id}]"


class MessageBusModule(XYZBaseModule):
    """
    MessageBus communication module.

    Enables Agents to communicate with each other via the MessageBus service.
    Provides MCP tools for messaging, channel management, and agent discovery.

    Instance level: Agent-level (one per Agent, is_public=True).
    """

    # =========================================================================
    # Configuration
    # =========================================================================

    def get_config(self) -> ModuleConfig:
        return ModuleConfig(
            name="MessageBusModule",
            priority=5,
            enabled=True,
            description=(
                "Agent-to-agent communication via message bus. "
                "Provides tools for sending/receiving messages, managing channels, "
                "and discovering other agents."
            ),
            module_type="capability",
        )

    # =========================================================================
    # MCP Server
    # =========================================================================

    async def get_mcp_config(self) -> Optional[MCPServerConfig]:
        return MCPServerConfig(
            server_name="message_bus_module",
            server_url=f"http://{mcp_host()}:{MESSAGE_BUS_MCP_PORT}/sse",
            type="sse",
        )

    def create_mcp_server(self) -> Optional[Any]:
        try:
            # Use the official mcp SDK's FastMCP (same as every other module)
            # so FASTMCP_HOST, TransportSecuritySettings, and the shared
            # module_runner._run_mcp_in_thread configuration all apply
            # uniformly. The standalone `fastmcp` v2 package has a different
            # API and does not honour those settings, which caused this MCP
            # to silently fail cross-container reachability.
            from mcp.server.fastmcp import FastMCP

            mcp = FastMCP("message_bus_module")
            mcp.settings.port = MESSAGE_BUS_MCP_PORT

            from ._message_bus_mcp_tools import register_message_bus_mcp_tools
            register_message_bus_mcp_tools(mcp, get_message_bus_fn=_get_default_bus_async)
            # The team work board rides the same MCP server: its items are
            # scoped to a team ROOM, which is a bus channel, so an agent that
            # can talk in the room is exactly the agent that can maintain its
            # board. Separate file, separate state machine — see
            # _work_board_mcp_tools for the platform/model write boundary.
            from ._work_board_mcp_tools import register_work_board_mcp_tools
            register_work_board_mcp_tools(mcp)

            logger.info(f"MessageBusModule MCP server created on port {MESSAGE_BUS_MCP_PORT}")
            return mcp
        except Exception as e:
            logger.exception(f"Failed to create MessageBusModule MCP server: {e}")
            return None

    # =========================================================================
    # Reply surface (origin-aware declaration)
    # =========================================================================

    def owns_working_source(self, working_source: Any) -> bool:
        """This module is the origin of MESSAGE_BUS turns — the collection
        sorts the origin module's declaration first, so the bus delivery
        tool becomes the turn's default reply tool."""
        return working_source_matches(working_source, WorkingSource.MESSAGE_BUS.value)

    async def get_expressive_tools(self, ctx_data: Any = None) -> list[str]:
        """Bus-triggered turns deliver through the bus tools — declare them
        as the reply surface so the framework's reply reminder names tools
        that actually reach whoever contacted the agent (2026-08-01: with
        only the owner-chat tool declared, finished work ended as
        undelivered plain text or was misdelivered to the owner's chat).

        Gated:
        - not a bus turn → nothing (advertising bus tools on a chat turn
          would invite replying to the owner over the bus);
        - no ctx → nothing (never advertise a surface for an unknown
          origin);
        - team room → nothing. NOTE: the PRIMARY team-room gate lives in
          the collection site ([[context_runtime]]), which empties the
          whole turn's surface before ever calling this method — the
          check here is a second line of defense keeping THIS
          declaration correct if the module is queried directly.
        """
        if not self.owns_working_source(getattr(ctx_data, "working_source", None)):
            return []
        extra = getattr(ctx_data, "extra_data", None) or {}
        if extra.get(BUS_TEAM_ROOM_EXTRA_KEY):
            return []
        config = await self.get_mcp_config()
        return [
            f"mcp__{config.server_name}__bus_send_message",
            f"mcp__{config.server_name}__bus_send_to_agent",
        ]

    # =========================================================================
    # Instructions — natural language guidance for the agent
    # =========================================================================

    def _static_instruction_parts(self) -> list:
        """The usage-rules half of the instruction — constant for a given
        agent (only self.agent_id is baked in), so it can live in the
        byte-stable system prompt (R4 turn-context relocation)."""
        return [
            "## MessageBus — Agent-to-Agent Communication",
            "",
            "MessageBus is your **inter-agent messaging channel**. Use it to collaborate with other Agents, "
            "exchange information, coordinate tasks, or reach out to contacts you cannot talk to directly.",
            "",
            f"Your agent ID: `{self.agent_id}`",
            "",
            "### When to Use MessageBus",
            "- You need to **contact another Agent** (ask a question, share information, coordinate work)",
            "- Your owner asks you to **send a message** to another agent",
            "- You want to **proactively reach out** based on your current task (e.g., gather intel, request help)",
            "- Use `bus_search_agents` to discover agents you haven't talked to yet",
            "",
            "### Available Tools",
            "- **bus_send_to_agent**: Direct-message another agent by `agent_id` (auto-creates a DM channel)",
            "- **bus_send_message**: Send a message to an existing channel (supports @mentions)",
            "- **bus_create_channel**: Create a new channel and invite members",
            "- **bus_get_messages**: Read recent history of a channel",
            "- **bus_search_agents**: Discover agents by capability or description",
            "- **bus_get_channel_members**: List channel members",
            "- **bus_get_agent_profile**: View another agent's profile",
            "- **bus_leave_channel**: Leave a channel you no longer need",
            "- **bus_kick_member**: Remove another agent from a channel (creator only)",
            "",
            "### DM (1-on-1) Workflow",
            "1. Call `bus_send_to_agent(to_agent_id='agent_xxx', content='...')`",
            "2. A direct channel is auto-created on first use; subsequent messages reuse it",
            "",
            "### Group Chat Workflow",
            "1. Call `bus_create_channel(name='Project Alpha Coordination', members='agent_a,agent_b')`",
            "2. Use `bus_send_message(channel_id=..., content=..., mention_list=...)` to talk",
            "3. **Always provide a meaningful channel `name`** — e.g., 'Sales Sync' not 'Untitled'",
            "",
            "### @Mention Rules (Group Channels)",
            "In group channels, **only @-mentioned agents are activated** by your message. "
            "Mentioning another agent **triggers it to run a full agent turn** — use mentions deliberately:",
            "- **Mention specific agents**: `mention_list='agent_a,agent_b'` — only they are triggered",
            "- **Mention everyone**: `mention_list='@everyone'` — **all** channel members are triggered (use sparingly)",
            "- **No mention_list**: nobody is triggered; the message is delivered passively",
            "- In **DM channels**, `mention_list` is ignored — the recipient is always triggered",
            "",
            "### Message Source Recognition",
            # This section described an INPUT PREFIX that has never existed.
            #
            # The code that would have produced it (`hook_data_gathering` step
            # 5) was dead twice over: it gated on `extra_data["working_source"]`
            # — a key nothing writes, because `working_source` is a ContextData
            # FIELD (`context_runtime.py:147`) while `extra_data` only carries
            # `trigger_extra_data` — and it wrote its result to
            # `extra_data["input_content"]`, which had no reader anywhere; the
            # consumed input is the FIELD `ctx_data.input_content`. So every
            # rule here pointed at a marker no turn has ever carried, and the
            # errand playbook below waited for a cue that could not fire.
            #
            # The branch is gone (iron rule #2 — delete, don't shim). These
            # rules now describe the tags that DO reach the model: the ones on
            # the Unread Messages list in this module's per-turn context.
            #
            # The example is generated by the same helper the list uses, so the
            # two cannot drift — the previous version taught a four-field tag
            # against a three-field renderer, which mattered the moment the
            # rules started telling the agent to READ the sender out of it.
            "Your **Unread Messages** list (in the MessageBus turn context) tags every entry with "
            f"its sender and channel, e.g.: `{_bus_tag('agent_xxx', 'ch_yyy')}` — sender first, "
            "then the channel",
            # The tag marks the ROUTE, not the species of whoever sent it. A
            # team room carries its owner's own messages over the bus (sender
            # `usr_<id>`), so the old flat "another agent, NOT from your owner"
            # was false exactly where a person is waiting, and it arrived bolted
            # to a rule that says to drop the pleasantries. The room's own
            # prompt renders that same sender as "User"; two readings of one row.
            "- A `[MessageBus · ...]` entry arrived over the bus rather than through your owner's "
            "main chat window. It is usually another agent — but **a person can speak on the bus "
            "too** (a team room carries its owner's own messages, shown as `User`), so read the "
            "sender instead of assuming a machine",
            "- An entry whose sender is `[system]` is the PLATFORM narrating something it did — not "
            "a teammate, and not someone to answer or @mention",
            "- Talking to an **agent** is peer-to-peer — be concise, professional, task-focused. When "
            "the sender is a person, talk to them like one",
            # Deliberately NOT a claim about what an untagged turn is.
            #
            # The line that stood here said "no tag ⇒ from your owner via the
            # main chat interface", which an IM turn contradicts in the same
            # context window (`channel/channel_prompts.py`) and a job turn has
            # no human for at all. The first rewrite made it "no tag ⇒ did not
            # arrive over the bus" — which was false on 100% of bus turns,
            # because no turn's INPUT has ever carried a tag. Both were the same
            # mistake: inferring the turn's origin from the absence of a marker
            # this module controls. Where a turn came from is stated by the
            # turn's own prompt, and that is all this block may say about it.
            "- These tags describe your unread QUEUE, not the message that started this turn. What "
            "triggered this turn is stated by this turn's own prompt — do not infer it from the "
            "presence or absence of a tag here",
            "",
            "### Autonomy — Be Proactive",
            "You are expected to handle bus messages **autonomously**, not as a passive intermediary.",
            "- When another agent asks you a question within your capabilities, **answer it directly** — do NOT ask your owner for permission first",
            "- When another agent requests your help with a task you can perform, **perform it and reply with the result**",
            "- Treat bus messages as real work, just like requests from your owner",
            "- Only escalate to your owner if the request is outside your capabilities, requires owner-specific approval, or involves sensitive decisions",
            "",
            "### Reply Discipline — CRITICAL (prevents infinite loops)",
            "Autonomy does NOT mean replying to everything. A reply triggers the other agent to run another turn, which can cascade into loops. Apply these rules:",
            # The species claim, in imperative form. Deleting it from the
            # Source Recognition rule above and leaving it here would have kept
            # the harm intact and only removed its justification: this is the
            # half with the BEHAVIOUR attached, and it re-asserts "the
            # counterparty is a machine" on its own authority. A team room's
            # owner posts over the bus, so a flat antecedent aims the
            # skip-pleasantries rule straight at a person.
            #
            # The brevity half carries the ping-pong P0 and is true toward any
            # peer, so it is scoped rather than dropped.
            "- **When the other party is another agent, it is not a human.** Skip pleasantries, skip warm-up phrases. Brevity beats politeness — a one-sentence answer is better than three; a single number, list, or status word is better than a sentence wrapping it. Agents do not need to feel acknowledged. When the sender is a PERSON (see Message Source Recognition), talk to them like one.",
            "- **Silence when the thread is done** — if the other party only acknowledges ('thanks', 'got it', '好的', '谢谢'), do NOT reply again. The conversation has reached a natural end.",
            "- **Do NOT ping-pong** — once you've answered a question and the other party has acknowledged, stop. Another reply adds zero value and triggers another round.",
            # Observed 2026-08-03 on a live turn: 小雀 relayed its owner's
            # question, 羽书 classified it as "纯转发" and stayed silent per
            # Reply Discipline — so the human who asked never got an answer.
            # Silence is for ACKNOWLEDGEMENTS, never for questions.
            "- **A question is never ping-pong — answer it.** If another agent asks you something you can answer, "
            "answering IS the substance. This includes a question they are relaying **on their owner's behalf** "
            "('X wants to know what you are working on'): that a message is 'just forwarded' is NOT a reason for "
            "silence — a human is waiting at the other end of it. Reporting the same status to your own owner does "
            "not discharge the request; the agent who asked cannot see what you told your owner. Reply to the asker.",
            # 2026-08-01 briefing squad: five analysts did real research and
            # ended their turns with the results as plain text — nothing was
            # delivered. Silence rules are for empty substance; a produced
            # result is the opposite of empty.
            #
            # The DUTY is stated here; the MECHANISM is not, because this block
            # does not know which surface the turn is on and the two surfaces
            # want opposite things. Naming only the tool made this the loudest
            # sentence a team room contradicts: there the plain text IS the
            # reply (the trigger posts it) and calling a delivery tool
            # double-posts, so "plain text delivers NOTHING" was word-for-word
            # backwards against the team prompt in the same context window.
            # Same resolution as the visibility rewrite two rules down — say
            # what holds everywhere, point at the turn for the rest.
            #
            # EXCEPTION-FORM, team case first and phrased as a PROHIBITION. The
            # first draft was a two-branch "when X do A; when Y do B", and X
            # ("a bus delivery tool is offered") is TRUE on a team turn: the
            # team gate empties the expressive DECLARATION only
            # (`context_runtime`), while the tool schemas stay in context
            # because this module has no `get_disallowed_tools` override. Both
            # branches therefore matched, the sentence stated no precedence,
            # and the reachable branch was the one that double-posts. A flat
            # tool list beating a per-turn instruction is a measured failure
            # here, not a hypothetical (see nexus_power prompts/library.py).
            "- **Finished work is never ping-pong — deliver it.** When you complete something another "
            "agent asked for (research, an answer, a document), the result has to REACH them; a turn "
            "that ends with the work sitting only in your own reasoning delivered nothing. If this "
            "turn's prompt tells you your reply is posted for you **without a tool call**, then "
            "writing it IS delivering it — do NOT also call a delivery tool, that sends it twice. "
            "Otherwise send the result with `bus_send_message` / `bus_send_to_agent`.",
            "- **Do NOT repeat yourself** — if you've already said X, do not rephrase X just to fill space.",
            "- **Substance only** — reply only when you have new information, a concrete answer, a clarifying question, or a task result. Do not reply with filler like 'I'm thinking about it', 'got your message', 'will get back to you'.",
            # "Just stop the turn" is a rule about TOOL CALLS, and it only adds
            # up to silence on a surface where nothing else delivers. Where the
            # reply auto-posts, leftover text is still a message the room
            # receives — so not calling a tool is not the same act as saying
            # nothing, and the rule has to name the one that is.
            #
            # The old tail ("the unread cursor advances appropriately") is gone
            # rather than rewritten: it was a third vague claim about the same
            # cursor the resurfacing rule below states precisely and scopes.
            # "to the bus conversation" is load-bearing, not padding. The old
            # text named two bus tools and so could only ever be read as a rule
            # about the bus; "end the turn with no reply text at all" is
            # absolute, and this same block obliges an owner relay 40 lines
            # down ("never suppresses reporting back to your owner"). Silence
            # toward a peer must not read as silence toward the person waiting.
            "- **If the substance is empty, choose silence explicitly.** If after reading the bus message you have nothing new to add, no concrete answer, no clarifying question worth asking — do not call `bus_send_message` or `bus_send_to_agent`, and end the turn with no reply text to the bus conversation at all. Silence is producing NOTHING, not producing something short: where a surface posts your reply for you, whatever text you leave behind is still a message somebody receives.",
            # Scoped to direct messages on purpose. In a DM the unread list IS
            # the queue, so declining to answer really does defer the item. A
            # team room delivers by rendering its scrollback into the turn, so
            # once a turn has run there the messages are read whether or not
            # the agent spoke — promising otherwise would be a rule the
            # platform stops keeping the moment the agent joins a team.
            "- **Ignored direct messages resurface** — a DM you choose not to "
            "reply to stays unread and appears again next turn. This is "
            "intentional: you can defer without forgetting.",
            # Says only what holds in EVERY room this block reaches. The old
            # wording ("in group channels you only see messages that @mention
            # you") is true of an ordinary bus group and false of a team room,
            # whose turn prompt carries the room's whole recent scrollback and
            # says so — two contradictory claims about the same room, in the
            # same context window. Visibility is a property of the room, so the
            # room's own prompt states it; this block may only speak to
            # activation, which is uniform.
            "- **An @mention decides who WAKES UP, not who can see.** What you "
            "can read in a given room is stated by that room's own prompt. "
            "Reply to what is addressed to you with intent (or decline via "
            "silence if a reply would just be filler).",
            "",
            "### When your owner asks about your inbox",
            "If the owner asks 'what messages do you have' or 'check your inbox', **report the contents directly**. Do not use this as an excuse to reply to peer agents — the owner is asking for a status report, not delegating.",
            "",
            # P1 2026-08-02: agents answered "I can't do that" to "ask X what
            # they're working on". The capability was always here — the model
            # reached for a contact-lookup tool, hit an error, and gave up. So
            # name the request shape and give it an explicit route.
            "### When your owner asks you to find something out FROM another agent",
            "Requests like 'ask the teaching expert what they're working on', 'check whether X finished', "
            "'find out if Y needs help' are **things you can do** — you have a message bus. "
            "**Never answer that you are unable to reach another agent.**",
            "1. Identify the target in your **Known Agents** list above (or `bus_search_agents` if it is not there). "
            "Use that exact `agent_id`.",
            "2. Ask them: `bus_send_to_agent(to_agent_id='agent_xxx', content='<the owner's question>')`. "
            "Do NOT use social-network / contact-lookup tools for this — those return contact details, not answers.",
            "3. Tell your owner you have asked, and that you will report back when the reply arrives. "
            "A reply is a **new turn**, not something you wait for inside this one.",
            # The recognition cue used to be "input tagged `[MessageBus · ...]`"
            # — the input prefix that never existed, so the one step of this
            # playbook that closes the loop back to the owner was keyed on a
            # signal that could not arrive. The reply shows up as a bus turn,
            # with the peer's answer in the unread list.
            "4. When their reply arrives (a new bus turn; their answer is in your Unread Messages), "
            "**relay the substance to your owner** "
            "with `send_message_to_user_directly`. That relay is the point of the errand — do not silently drop it. "
            "(Reply Discipline governs replies to the AGENT; it never suppresses reporting back to your owner.)",
            "If the target genuinely cannot be found, say who you looked for and ask your owner which agent they meant — "
            "that is a clarifying question, not a refusal.",
            "",
            "### When NOT to Call Tools",
            "- **Do NOT call `bus_get_unread`** — unread messages are already injected into your context automatically. Only call it if you suspect new messages arrived mid-turn.",
            "- **There is no bus registration tool** — your discovery entry is rebuilt from your profile and your installed skills on every turn. "
            "To change what peers see, set your name/description with `update_agent_profile` (Awareness); capabilities are derived, never declared.",
            "- **Do NOT call `bus_get_messages`** for channels whose history you already have in context.",
        ]

    def _volatile_context_parts(self, ctx_data: ContextData) -> list:
        """The three live data lists (Known Agents / Your Channels / Unread
        Messages) — changed mid-session by bus tools and consumed unreads,
        so they are per-turn volatile. Rendering (caps, order, wording) is
        unchanged from the pre-R4 in-instruction rendering; only the
        destination differs by the relocation flag (R4: relocated, never
        dropped)."""
        parts = []

        # Known agents (capped + filtered)
        known = ctx_data.extra_data.get("bus_known_agents", [])
        if known:
            parts.append("")
            parts.append(f"### Known Agents (top {min(len(known), MAX_KNOWN_AGENTS_IN_CONTEXT)})")
            for a in known[:MAX_KNOWN_AGENTS_IN_CONTEXT]:
                name = a.get("agent_name") or a.get("agent_id", "")
                desc = a.get("agent_description") or a.get("description", "")
                aid = a.get("agent_id", "")
                line = f"- `{aid}` — {name}"
                # An unset description is rendered as NOTHING, never as the
                # creation placeholder: printing "a new agent ready for
                # configuration" next to every peer is what left "ask the
                # teaching expert" with nothing to aim at, and made this list
                # read as "none of these agents are usable" (P1 section 02).
                if not is_agent_description_unset(desc):
                    line += f": {desc[:80]}"
                # `via_team` was computed for every peer and read by nobody.
                # This list mixes teammates with every other agent the owner
                # has, so an agent reaching for help could not tell "already in
                # a room with me" from "a stranger I would have to DM cold".
                if a.get("via_team"):
                    line += " (teammate)"
                parts.append(line)

        # Channels (capped)
        channels = ctx_data.extra_data.get("bus_channels", [])
        if channels:
            parts.append("")
            parts.append(f"### Your Channels (top {min(len(channels), MAX_CHANNELS_IN_CONTEXT)})")
            for ch in channels[:MAX_CHANNELS_IN_CONTEXT]:
                cid = ch.get("channel_id", "")
                cname = ch.get("name", "unnamed")
                ctype = ch.get("channel_type", "group")
                parts.append(f"- `{cid}` — {cname} ({ctype})")

        # Unread messages (capped, with source tag preview)
        unread = ctx_data.extra_data.get("bus_unread_messages", [])
        if unread:
            # The window is what we render; the total is what the reader needs
            # in order to know a window is what it is looking at. They stopped
            # being the same number when the cap moved into the query.
            shown = len(unread)
            total = int(ctx_data.extra_data.get("bus_unread_total") or shown)
            parts.append("")
            parts.append(f"### Unread Messages: {total} (showing {shown})")
            # Same scoping as the static rule above, for the same reason —
            # and it matters more here, because this header sits directly on a
            # list that MIXES team-room messages in. A team room clears its
            # cursor once a turn has rendered it, so "ignored messages stay
            # unread" is false for part of what is printed underneath.
            parts.append(
                "> Remember: apply Reply Discipline. A direct message you do "
                "not answer stays unread; what a room keeps unread is stated "
                "by that room's own prompt."
            )
            for m in unread[:MAX_UNREAD_IN_CONTEXT]:
                content = (m.get("content") or "")[:200]
                # `msg_type` is carried so platform lines are labelled rather
                # than quoted as a member. This list has no type filter (and
                # neither does the unread predicate), so patrol lines, stop and
                # bulletin notices are unread for every member and land here —
                # the room's own prompt labels them `[system]`, and until now
                # this list printed them as a teammate with a synthetic name.
                tag = _bus_tag(
                    m.get("from_agent"), m.get("channel_id", ""), m.get("msg_type")
                )
                parts.append(f"- `{tag}` {content}")

        return parts

    async def get_instructions(self, ctx_data: ContextData) -> str:
        """Usage rules, plus (flag OFF only) the live data lists.

        With the R4 relocation flag ON the output is byte-stable across
        turns and the lists travel via get_turn_context(); flag OFF keeps
        the legacy single-block rendering, byte-identical to pre-R4.
        """
        parts = self._static_instruction_parts()
        if not settings.prompt_turn_context_relocation_enabled:
            parts = parts + self._volatile_context_parts(ctx_data)
        return "\n".join(parts)

    async def get_turn_context(self, ctx_data: ContextData) -> str:
        """Per-turn volatile span: the Known Agents / Your Channels /
        Unread Messages lists, under a stable heading."""
        volatile = self._volatile_context_parts(ctx_data)
        if not volatile:
            return ""
        return "\n".join(["### MessageBus — Current State", *volatile])

    # =========================================================================
    # Hooks
    # =========================================================================

    async def hook_data_gathering(self, ctx_data: ContextData) -> ContextData:
        """
        Inject MessageBus context into agent data.

        1. Auto-register current agent in bus_agent_registry (idempotent)
        2. Fetch known agents (filtered + capped)
        3. Fetch unread messages (capped)
        4. Fetch channel list (capped)
        5. If this execution was triggered BY a bus message, prefix the input
           with a source tag so the agent can recognize where it came from.
        """
        try:
            bus = await _get_default_bus_async()
            if bus is None:
                return ctx_data

            # --- 1. Keep this agent's peer-discovery row true ---
            #
            # Was an inline write with `capabilities=[]` hardcoded and the raw
            # `agent_description` (i.e. the creation placeholder) republished —
            # which is what made `bus_search_agents` answer nothing for every
            # query and told askers that a configured peer was "a new agent
            # ready for configuration" (P1 section 02, all 488 prod rows). The policy
            # now lives in ONE service that creation / rename / config / skill
            # install also call, so discovery no longer waits for a first turn;
            # this call is the idempotent per-turn backstop.
            try:
                db = await _get_shared_db()
                if db:
                    from xyz_agent_context.message_bus.agent_discovery_sync import (
                        sync_agent_discovery,
                    )
                    await sync_agent_discovery(db, self.agent_id)
            except Exception as e:
                logger.debug(f"Failed to sync agent discovery row: {e}")

            # --- 2. Fetch known agents ---
            #
            # Visibility rule (subproject 1, 议题 7 follow-up):
            #
            #   * If THIS agent belongs to one or more teams → only same-team
            #     members (across all of this agent's teams) + public agents.
            #     Same-owner agents NOT in any of my teams are excluded —
            #     team is the messageable boundary once you've opted in.
            #
            #   * If this agent is in NO team → fall back to legacy behavior:
            #     same-owner agents + public. (Backwards-compatible default
            #     for users who haven't created any team.)
            #
            # This way "team" actually scopes who an agent can talk to via
            # the bus; users who don't use teams keep the old "everyone I own"
            # behavior unchanged.
            known_agents = []
            try:
                db = await _get_shared_db()
                if db:
                    agent_row = await db.get_one("agents", {"agent_id": self.agent_id})
                    my_owner = agent_row.get("created_by", "") if agent_row else ""

                    # Resolve my team-mates (set of agent_ids I share at least
                    # one team with). Empty set → I'm in no team → legacy mode.
                    from xyz_agent_context.repository import TeamMemberRepository
                    team_repo = TeamMemberRepository(db)
                    my_team_ids = await team_repo.list_teams_by_agent(self.agent_id)
                    teammate_ids: set = set()
                    if my_team_ids:
                        for mate in await team_repo.list_team_mates(self.agent_id):
                            teammate_ids.add(mate["agent_id"])

                    use_team_scope = bool(my_team_ids)

                    all_agents = await db.get("agents", {})
                    for a in all_agents:
                        aid = a.get("agent_id")
                        if aid == self.agent_id:
                            continue
                        same_owner = my_owner and a.get("created_by") == my_owner
                        is_public = bool(a.get("is_public", 0))
                        if use_team_scope:
                            # In team mode: only team-mates (same owner or not)
                            # plus public agents.
                            if aid not in teammate_ids and not is_public:
                                continue
                        else:
                            # Legacy / no-team mode: same owner OR public.
                            if not (same_owner or is_public):
                                continue
                        known_agents.append({
                            "agent_id": aid,
                            "agent_name": a.get("agent_name", ""),
                            "agent_description": a.get("agent_description", ""),
                            "is_public": a.get("is_public", 0),
                            "created_by": a.get("created_by", ""),
                            # Whether this agent shares a team with us —
                            # rendered as "(teammate)" in the list below.
                            "via_team": aid in teammate_ids,
                        })
                        if len(known_agents) >= MAX_KNOWN_AGENTS_IN_CONTEXT:
                            break
                if known_agents:
                    ctx_data.extra_data["bus_known_agents"] = known_agents
            except Exception as e:
                logger.debug(f"Failed to fetch known agents: {e}")

            # --- 3. Fetch unread messages (capped) ---
            # The cap is pushed into the query, and it selects the NEWEST ones.
            # Slicing an oldest-first list in Python (what this used to do) kept
            # handing the model the most ancient messages in the backlog — and
            # since the read cursor never advanced in team rooms, that window
            # was frozen: the same 20 lines, turn after turn, described as if
            # they were the room's current state.
            unread_models = []
            try:
                unread = await bus.get_unread(
                    self.agent_id, limit=MAX_UNREAD_IN_CONTEXT
                )
                if unread:
                    unread_models = unread
                    ctx_data.extra_data["bus_unread_messages"] = [
                        msg.model_dump() for msg in unread_models
                    ]
                    # The total is a separate question once the fetch is capped:
                    # len() of a window always equals the window.
                    ctx_data.extra_data["bus_unread_total"] = await bus.count_unread(
                        self.agent_id
                    )
            except Exception as e:
                logger.debug(f"Failed to fetch unread messages: {e}")

            # --- 4. Fetch channels (capped) ---
            try:
                rows = await bus._db.execute(
                    "SELECT c.* FROM bus_channels c "
                    "JOIN bus_channel_members cm ON c.channel_id = cm.channel_id "
                    "WHERE cm.agent_id = %s "
                    "ORDER BY c.created_at DESC "
                    "LIMIT %s",
                    (self.agent_id, MAX_CHANNELS_IN_CONTEXT),
                )
                if rows:
                    ctx_data.extra_data["bus_channels"] = [dict(r) for r in rows]
            except Exception as e:
                logger.debug(f"Failed to load bus channels: {e}")

            # --- 5. (removed) input source tag ---
            #
            # A branch used to sit here prefixing `[MessageBus · sender ·
            # channel]` onto the turn's input. It never ran, and could not have
            # worked if it had:
            #
            #   * its guard read `extra_data["working_source"]`, and nothing in
            #     the repo writes that key — `working_source` is a ContextData
            #     FIELD, seeded at `context_runtime.py:147`, while `extra_data`
            #     is filled from `trigger_extra_data` alone (the correct read is
            #     `working_source_matches(ctx_data.working_source, …)`, which
            #     `get_expressive_tools` in this same file already does);
            #   * it wrote to `extra_data["input_content"]`, which had no reader
            #     in the codebase. The input the model actually receives is the
            #     FIELD `ctx_data.input_content` (`context_runtime.py:1032`).
            #
            # It is deleted rather than repaired because switching it on is a
            # live change to two shipped prompts — a team turn's input IS the
            # whole `[Team Group Chat]…` prompt and a DM turn's is
            # `_build_prompt`'s output, and both already name their sender in
            # their own words, so a machine prefix in front of them is a product
            # decision, not a bug fix. The instructions above now describe the
            # tags that genuinely reach the model, on the unread list.

        except Exception as e:
            logger.exception(f"MessageBusModule hook_data_gathering failed: {e}")
        return ctx_data

    async def hook_after_event_execution(
        self, params: HookAfterExecutionParams
    ) -> None:
        """
        Post-execution cleanup for MessageBus.

        Selective mark_read: only mark messages as read if the agent actually
        replied to them. Messages the agent ignored stay unread and will
        resurface on the next turn — this is the "silence is acceptable"
        mechanism.

        We detect replies by inspecting trace for bus_send_message and
        bus_send_to_agent tool calls.
        """
        # Only process if this was a bus-triggered execution OR if the agent
        # actually sent bus messages this turn (could be user-initiated outreach)
        try:
            bus = await _get_default_bus_async()
            if bus is None:
                return

            # Extract channel IDs that were replied to
            replied_channels: set[str] = set()
            replied_agents: set[str] = set()  # For bus_send_to_agent

            if params.trace and params.trace.agent_loop_response:
                for response in params.trace.agent_loop_response:
                    tool_name = getattr(response, "tool_name", None)
                    tool_input = getattr(response, "tool_input", None)

                    # Tool names come through as mcp__message_bus_module__bus_send_message
                    # or just bus_send_message depending on how the SDK reports them
                    if not tool_name:
                        continue
                    if not isinstance(tool_input, dict):
                        continue

                    if "bus_send_message" in tool_name:
                        cid = tool_input.get("channel_id")
                        if cid:
                            replied_channels.add(cid)
                    elif "bus_send_to_agent" in tool_name:
                        target = tool_input.get("to_agent_id")
                        if target:
                            replied_agents.add(target)

            # Only mark read for channels where we actually replied
            if not replied_channels and not replied_agents:
                logger.debug(
                    f"MessageBus: agent {self.agent_id} did not reply to any bus "
                    f"messages this turn — unread messages stay unread"
                )
                return

            # Get all unread and filter to only the replied-to conversations
            unread = await bus.get_unread(self.agent_id)
            if not unread:
                return

            to_mark = []
            for m in unread:
                if m.channel_id in replied_channels:
                    to_mark.append(m.message_id)
                    continue
                # For bus_send_to_agent: we sent a DM to some agent. Mark read
                # any unread DM from that same agent (the DM channel includes both).
                if m.from_agent in replied_agents:
                    to_mark.append(m.message_id)

            if to_mark:
                await bus.mark_read(self.agent_id, to_mark)
                logger.info(
                    f"MessageBus: selective mark_read — {len(to_mark)}/{len(unread)} "
                    f"messages marked read for agent {self.agent_id} "
                    f"(replied to {len(replied_channels)} channels, {len(replied_agents)} DMs)"
                )
            else:
                logger.debug(
                    f"MessageBus: agent {self.agent_id} replied to channels "
                    f"{replied_channels} but no matching unread messages to mark"
                )
        except Exception as e:
            logger.exception(f"MessageBusModule hook_after_event_execution failed: {e}")


# =============================================================================
# Module-level helpers
# =============================================================================

_bus_instances: dict[int, Any] = {}  # keyed by event loop id


async def _get_default_bus_async():
    """Get or create a LocalMessageBus bound to the current event loop.

    Uses ``get_db_client()`` which already handles event-loop changes and
    creates a fresh aiomysql pool on the correct loop.  The bus instance is
    cached per-loop so subsequent calls on the same loop are free.
    """
    import asyncio

    loop = asyncio.get_running_loop()
    loop_id = id(loop)

    if loop_id in _bus_instances:
        return _bus_instances[loop_id]

    try:
        from xyz_agent_context.message_bus import LocalMessageBus
        from xyz_agent_context.utils.db.db_factory import get_db_client

        db = await get_db_client()
        backend = db._backend
        if backend is None:
            logger.warning("MessageBus: database backend is None")
            return None

        bus = LocalMessageBus(backend=backend)
        _bus_instances[loop_id] = bus
        logger.info(f"MessageBus: created instance for event loop {loop_id}")
        return bus
    except Exception as e:
        logger.exception(f"Failed to initialize default MessageBus: {e}")
        return None


def _get_default_bus():
    """Sync wrapper — only works if a bus was already created for the current loop."""
    import asyncio
    try:
        loop = asyncio.get_running_loop()
        return _bus_instances.get(id(loop))
    except RuntimeError:
        return None


async def _get_shared_db():
    """Get the shared AsyncDatabaseClient."""
    try:
        from xyz_agent_context.utils.db.db_factory import get_db_client
        return await get_db_client()
    except Exception as e:
        logger.debug(f"Failed to get shared DB client: {e}")
        return None
