"""
@file_name: subprocess_env.py
@author: Bin Liang
@date: 2026-09-08
@description: Make ``nxplugins.<id>`` importable in a child process (a plugin's stdio MCP server).

``nxplugins`` is a synthetic namespace served by an in-process meta-path finder,
so ``python -m nxplugins.acme_x.server`` in a fresh interpreter fails with
"No module named nxplugins" — which is exactly what the tool template's stdio
server does. This module writes a tiny real ``nxplugins`` package under the
plugin home; a child process that has that directory on ``PYTHONPATH`` imports
it first, and its ``__init__`` installs the finder and registers every plugin
from ``registry.json`` (backend dir + pip deps dir), after which the finder
serves the submodules as it does in the host.

``subprocess_env()`` is what a stdio server config carries in ``env``: the
``PYTHONPATH`` entry and the plugin home. The launcher merges it over the
process environment; nothing here copies ``os.environ``.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Mapping

from narranexus.kernel.plugins.importer import NAMESPACE
from narranexus.kernel.plugins.paths import ENV_PLUGIN_HOME, plugin_home

_BOOTSTRAP = '''"""Generated by NarraNexus — do not edit.

Makes ``nxplugins.<plugin>`` importable in this process the way the host does it:
install the plugin finder and register every plugin from registry.json.
"""
from pathlib import Path as _Path

from narranexus.kernel.plugins.importer import install_synthetic_package as _install, plugin_finder as _finder
from narranexus.kernel.plugins.lifecycle import RegistryStore as _Store
from narranexus.kernel.plugins.paths import deps_dir as _deps_dir, registry_path as _registry_path

_finder()
try:
    _registry = _Store(path=_registry_path()).read()
except Exception:  # noqa: BLE001 — an unreadable registry means no plugins, not a crash
    _registry = None
for _pid, _rec in (_registry.plugins.items() if _registry is not None else ()):
    _root = _Path(_rec.path)
    _backend = _root / "backend"
    if (_backend / "__init__.py").is_file():
        try:
            _install(_pid, _backend)
        except Exception:  # noqa: BLE001 — one broken plugin must not hide the others
            continue
    _deps = _deps_dir(_pid, mode=_rec.mode, plugin_path=_root)
    if _deps.is_dir():
        _finder().register_deps(_pid, _deps)
'''


def bootstrap_dir() -> Path:
    """The directory to put on a child's ``PYTHONPATH`` (holds the ``nxplugins`` package)."""
    return plugin_home() / "run" / "pythonpath"


def ensure_bootstrap() -> Path:
    """Write the bootstrap package if missing or stale; returns ``bootstrap_dir()``."""
    root = bootstrap_dir()
    init = root / NAMESPACE / "__init__.py"
    if not init.is_file() or init.read_text(encoding="utf-8") != _BOOTSTRAP:
        init.parent.mkdir(parents=True, exist_ok=True)
        init.write_text(_BOOTSTRAP, encoding="utf-8")
    return root


def subprocess_env(extra: Mapping[str, str] | None = None) -> dict[str, str]:
    """Environment entries a plugin subprocess needs; ``extra`` (the spec's own env) wins."""
    root = ensure_bootstrap()
    env = {
        "PYTHONPATH": str(root),
        ENV_PLUGIN_HOME: str(plugin_home()),
    }
    if extra:
        env.update({str(k): str(v) for k, v in extra.items()})
        if "PYTHONPATH" in extra:
            env["PYTHONPATH"] = f"{root}{os.pathsep}{extra['PYTHONPATH']}"
    return env


__all__ = ["bootstrap_dir", "ensure_bootstrap", "subprocess_env"]
