"""
@file_name: test_auth_agents_directory_mysql.py
@author: Bin Liang
@date: 2026-09-07
@description: MySQL twin for the agents-directory channel UNION (channel/binding_tables): the GENERATED query — derived tables with index aliases, the channel name as a bound parameter, UNION ALL over branches with different active columns — executed on the dialect it can break on.

    docker run --rm -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=nxtest --name nx-mysql-test mysql:8
    export NARRANEXUS_MYSQL_TEST_URL=mysql://root:root@127.0.0.1:3306/nxtest
"""
from __future__ import annotations

from pathlib import Path

import pytest
import pytest_asyncio

from narranexus.platform.channel import credential_codec
from narranexus.platform.channel.binding_tables import bound_channels_query, channel_binding_sources
from narranexus.platform.channel.credential_store import TABLE, GenericCredentialStore
from narranexus.platform.utils.db.database import AsyncDatabaseClient
from narranexus.platform.utils.db.db_backend_mysql import MySQLBackend
from narranexus.platform.utils.db.schema_registry import auto_migrate

from tests.mysql_dialect import mysql_configured, mysql_url, parse_mysql_url, skip_reason

pytestmark = pytest.mark.skipif(not mysql_configured(), reason=skip_reason("the agents-directory channel UNION generated by channel/binding_tables"))

A1, A2 = "agent_mysqldir_1", "agent_mysqldir_2"


@pytest.fixture(autouse=True)
def _key_dir(tmp_path: Path):
    credential_codec.use_key_dir(tmp_path / "keys")
    yield
    credential_codec.use_key_dir(None)


@pytest_asyncio.fixture
async def mysql_client():
    backend = MySQLBackend(parse_mysql_url(mysql_url()))
    await backend.initialize()
    await auto_migrate(backend)
    client = await AsyncDatabaseClient.create_with_backend(backend)
    for aid in (A1, A2):
        await client.delete(TABLE, {"agent_id": aid})
        await client.delete("instance_homeassistant_bindings", {"agent_id": aid})
    yield client
    for aid in (A1, A2):
        await client.delete(TABLE, {"agent_id": aid})
        await client.delete("instance_homeassistant_bindings", {"agent_id": aid})
    await client.close()


@pytest.mark.asyncio
async def test_generated_union_runs_on_mysql(mysql_client):
    import narranexus.platform.module_system  # noqa: F401 — registers the builtin channel descriptors

    store = GenericCredentialStore(mysql_client)
    await store.upsert("telegram", A1, {"bot_token": "t1"}, enabled=True)
    await store.upsert("telegram", A2, {"bot_token": "t2"}, enabled=False)
    sources = channel_binding_sources()
    assert {s.channel for s in sources} >= {"telegram", "home_assistant"}
    query, params = bound_channels_query(sources, [A1, A2])
    rows = await mysql_client.execute(query, params)
    state = {(r["channel_name"], r["agent_id"]): bool(r["active"]) for r in rows}
    assert state[("telegram", A1)] is True and state[("telegram", A2)] is False
    assert not any(ch == "home_assistant" for ch, _ in state)
