"""
@file_name: gen_plugin_docs.py
@author: Bin Liang
@date: 2026-09-03
@description: Generate docs/plugins/slots.md from the kernel slot tree and contract versions.

Run ``uv run python scripts/dev/gen_plugin_docs.py --write`` after changing a slot or a
contract version; ``tests/nx_kernel/test_docs_generated.py`` fails when the committed
file is stale, so the reference for plugin authors cannot drift from the code.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from narranexus.contracts import API_VERSIONS, STABILITY
from narranexus.kernel.plugins.builtins import builtin_manifests
from narranexus.kernel.plugins.slots import build_kernel_slot_tree

DOCS = Path(__file__).resolve().parents[2] / "docs" / "plugins"
OUTPUT = DOCS / "slots.md"

HOST_API_TABLE = [
    ("version / api.ui", "host version string; UI contract version (1)"),
    ("pluginId", "this plugin's id"),
    ("libs.react / reactDom / router / zustand / i18next / icons", "the host's single copies; plugin bundles mark them external"),
    ("registries.pages / sidebar / panels / settingsSections / commands / themes", "the contribution registries"),
    ("register(registry, id, value)", "register as this plugin; disposer tracked; may replace only its own gate entry"),
    ("http.request(path, init) / http.prefix", "JSON request with the session auth (relative paths only); `/api/x/<id>`"),
    ("i18n.addResourceBundle(lng, res) / i18n.t(key)", "strings in the `plugin:<id>` namespace"),
    ("log.error(error, context)", "reported to the error sink, attributed to this plugin"),
    ("subscriptions / dispose()", "everything registered, unwound on deactivate"),
]


def render() -> str:
    lines = [
        "# Plugin slots and contract versions",
        "",
        "Generated by `scripts/dev/gen_plugin_docs.py` — do not edit by hand.",
        "",
        "## Contract versions",
        "",
        "| Kind | Version | Stability |",
        "|---|---|---|",
    ]
    for kind in sorted(API_VERSIONS):
        lines.append(f"| `{kind}` | {API_VERSIONS[kind]} | {STABILITY[kind].value} |")
    lines += [
        "",
        "## Slots",
        "",
        "Path → arity → contract → default provider → owner. `distribution-only` slots can be",
        "bound only from the distribution or default layers.",
        "",
        "| Path | Arity | Contract | Default | Owner | Flags | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in build_kernel_slot_tree().to_rows():
        flags = ", ".join(f for f, on in (("distribution-only", row["distribution_only"]),) if on)
        lines.append(
            f"| `{row['path']}` | {row['arity']} | `{row['contract']}` | "
            f"{('`' + row['default'] + '`') if row['default'] else '—'} | `{row['owner']}` | "
            f"{flags or '—'} | {row['doc']} |"
        )
    lines += ["", "## Builtin plugins", "", "| Plugin | Version | Hosts | Provides | Quality |", "|---|---|---|---|---|"]
    for m in builtin_manifests():
        provides = ", ".join(f"`{p}`" for p in m.provides)
        lines.append(f"| `{m.id}` | {m.version} | {', '.join(m.hosts) or 'all'} | {provides} | {m.quality} |")
    return "\n".join(lines) + "\n"


def render_contributes() -> str:
    from narranexus.kernel.plugins.registries import SLOT_KINDS

    lines = [
        "# Contribution kinds",
        "",
        "Generated by `scripts/dev/gen_plugin_docs.py` — do not edit by hand.",
        "",
        "A plugin fills a slot by naming a symbol in `narranexus-plugin.json` → `provides`;",
        "the symbol is a `Contribution` (or a list of them) whose factory builds the contract type.",
        "`backend.hooks` values are `@hookimpl(name)` functions instead.",
        "",
        "| Slot | Kind | API version | Contract | Manifest key |",
        "|---|---|---|---|---|",
    ]
    tree = build_kernel_slot_tree()
    for row in tree.to_rows():
        if row["arity"] != "many":
            continue
        kind = SLOT_KINDS.get(row["path"], "—")
        version = API_VERSIONS.get(kind, "—") if kind != "—" else "—"
        lines.append(f"| `{row['path']}` | {kind} | {version} | `{row['contract']}` | `\"{row['path']}\": [\"pkg.module:SYMBOL\"]` |")
    lines += ["", "Frontend contributions are declared under `frontend.ui` (`pages`, `panels`, `commands`, `themes`) and registered by the plugin's bundle at activation.", ""]
    return "\n".join(lines) + "\n"


def render_events() -> str:
    from narranexus.contracts.agent.events import STAGE_HOOKS
    from narranexus.contracts.events import HOST_EVENTS, host_event_params

    lines = ["# Host events and stage hooks", "", "Generated by `scripts/dev/gen_plugin_docs.py` — do not edit by hand.", "", "## Host events", "", "| Event | Parameters |", "|---|---|"]
    for name in HOST_EVENTS:
        lines.append(f"| `{name}` | {', '.join(f'`{p}`' for p in host_event_params(name))} |")
    lines += ["", "## Stage hooks", "", "| Hook | Parameters | First result |", "|---|---|---|"]
    for name, (params, firstresult) in STAGE_HOOKS.items():
        lines.append(f"| `{name}` | {', '.join(f'`{p}`' for p in params)} | {'yes' if firstresult else 'no'} |")
    lines += ["", "Implement with `@hookimpl(\"<name>\")` and list the functions under `backend.hooks`.", ""]
    return "\n".join(lines) + "\n"


def render_host_api() -> str:
    lines = ["# Frontend HostAPI", "", "Generated by `scripts/dev/gen_plugin_docs.py` — do not edit by hand.", "", "What `activate(host)` receives (`frontend/src/platform/host.ts`). Nothing else is promised.", "", "| Member | Meaning |", "|---|---|"]
    for member, meaning in HOST_API_TABLE:
        lines.append(f"| `{member}` | {meaning} |")
    lines += ["", "Bundle with `@narranexus/sdk` `vitePreset()`: one ESM file, host libraries external.", ""]
    return "\n".join(lines) + "\n"


def render_all() -> dict[Path, str]:
    return {OUTPUT: render(), DOCS / "contributes.md": render_contributes(), DOCS / "events.md": render_events(), DOCS / "host-api.md": render_host_api()}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write docs/plugins/*.md")
    args = parser.parse_args()
    stale = []
    for path, text in render_all().items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path}")
        elif not path.is_file() or path.read_text(encoding="utf-8") != text:
            stale.append(path.name)
    if stale:
        print(f"stale generated docs: {stale}; run with --write", file=sys.stderr)
        return 1
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
