"""
@file_name: gen_plugin_docs.py
@author: Bin Liang
@date: 2026-09-03
@description: Generate docs/plugins/slots.md from the kernel slot tree and contract versions.

Run ``uv run python scripts/dev/gen_plugin_docs.py --write`` after changing a slot or a
contract version; ``tests/nx_kernel/test_docs_generated.py`` fails when the committed
file is stale, so the reference for plugin authors cannot drift from the code.
"""
from __future__ import annotations

import argparse
from pathlib import Path

from narranexus.contracts import API_VERSIONS, STABILITY
from narranexus.kernel.plugins.builtins import builtin_manifests
from narranexus.kernel.plugins.slots import build_kernel_slot_tree

OUTPUT = Path(__file__).resolve().parents[2] / "docs" / "plugins" / "slots.md"


def render() -> str:
    lines = [
        "# Plugin slots and contract versions",
        "",
        "Generated by `scripts/dev/gen_plugin_docs.py` — do not edit by hand.",
        "",
        "## Contract versions",
        "",
        "| Kind | Version | Stability |",
        "|---|---|---|",
    ]
    for kind in sorted(API_VERSIONS):
        lines.append(f"| `{kind}` | {API_VERSIONS[kind]} | {STABILITY[kind].value} |")
    lines += [
        "",
        "## Slots",
        "",
        "Path → arity → contract → default provider → owner. `distribution-only` slots can be",
        "bound only from the distribution or default layers.",
        "",
        "| Path | Arity | Contract | Default | Owner | Flags | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in build_kernel_slot_tree().to_rows():
        flags = ", ".join(f for f, on in (("distribution-only", row["distribution_only"]),) if on)
        lines.append(
            f"| `{row['path']}` | {row['arity']} | `{row['contract']}` | "
            f"{('`' + row['default'] + '`') if row['default'] else '—'} | `{row['owner']}` | "
            f"{flags or '—'} | {row['doc']} |"
        )
    lines += ["", "## Builtin plugins", "", "| Plugin | Version | Hosts | Provides | Quality |", "|---|---|---|---|---|"]
    for m in builtin_manifests():
        provides = ", ".join(f"`{p}`" for p in m.provides)
        lines.append(f"| `{m.id}` | {m.version} | {', '.join(m.hosts) or 'all'} | {provides} | {m.quality} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write docs/plugins/slots.md")
    args = parser.parse_args()
    text = render()
    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUTPUT}")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
