/**
 * @file_name: HtmlRendererEditing.test.tsx
 * @description: HtmlRenderer's half of per-element editing (spec A §3.2/3.3):
 * a bridge message from ITS OWN iframe → fetch the clean source → anchored
 * literal replace → PUT /content with the fetched bytes' hash. Anchor
 * failures surface the degrade-to-AI notice instead of writing anywhere.
 */

import { render, waitFor } from '@testing-library/react';
import { act } from 'react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { Artifact } from '@/types/artifact';
import { sha256Hex } from '@/lib/sha256';

const putContent = vi.fn();
vi.mock('@/services/artifactsApi', async (importOriginal) => {
  const mod = await importOriginal<typeof import('@/services/artifactsApi')>();
  return {
    ...mod,
    artifactsApi: {
      ...mod.artifactsApi,
      getRawUrl: vi.fn(async () => 'http://raw/dir/'),
      putContent: (...a: unknown[]) => putContent(...a),
    },
  };
});
vi.mock('@/hooks/useArtifactHeal', () => ({
  useArtifactHeal: () => ({
    modalOpen: false, candidates: [], message: '', busy: false,
    recoveryVersion: 0, attempt: vi.fn(), dismiss: vi.fn(),
  }),
}));
vi.mock('@/lib/tauri', () => ({
  isTauri: () => false,
  fetchArtifactViaTauri: vi.fn(async () => null),
}));

import HtmlRenderer from '../HtmlRenderer';

const SOURCE = '<html><body><h1>Old Title</h1><p>text</p></body></html>';

const ART: Artifact = {
  artifact_id: 'art_html01',
  agent_id: 'agent_x',
  user_id: 'user_y',
  session_id: 's',
  title: 'page',
  kind: 'text/html',
  description: null,
  pinned: false,
  team_id: null,
  // three segments → NOT a workspace-root entry → raw-url iframe path
  file_path: 'ws_dir/page/index.html',
  size_bytes: 10,
  created_at: '2026-08-19T00:00:00Z',
  updated_at: '2026-08-19T00:00:00Z',
};

function stubFetch() {
  const bytes = new TextEncoder().encode(SOURCE);
  vi.stubGlobal('fetch', vi.fn(async (_url: string, init?: RequestInit) => ({
    ok: true,
    status: init?.method === 'HEAD' ? 200 : 200,
    arrayBuffer: async () => bytes.buffer,
  })));
}

async function fireBridgeEdit(container: HTMLElement, data: Record<string, unknown>) {
  const iframe = container.querySelector('iframe')!;
  // `waitFor` above resolves off the DOM mutation that inserts the iframe, and
  // RTL runs it OUTSIDE the act environment — so React's passive effect that
  // re-registers the `message` listener against the freshly minted url may
  // still be queued. Dispatching now would hit the mount-time listener whose
  // `commitBridgeEdit` closes over `url === null` and returns immediately, and
  // the edit would be dropped for good (a ~0.5% flake). Flush the pending
  // effects first; this is a real ordering fix, not a timeout.
  await act(async () => {});
  await act(async () => {
    window.dispatchEvent(
      new MessageEvent('message', {
        data,
        source: iframe.contentWindow,
      }),
    );
  });
}

beforeEach(() => {
  putContent.mockReset();
  stubFetch();
});

describe('HtmlRenderer per-element editing', () => {
  it('asks for the bridge on the iframe src', async () => {
    const { container } = render(<HtmlRenderer artifact={ART} />);
    await waitFor(() => expect(container.querySelector('iframe')).not.toBeNull());
    expect(container.querySelector('iframe')!.getAttribute('src')).toContain('edit_bridge=1');
  });

  it('commits a bridge edit through the anchored replace + PUT pipeline', async () => {
    putContent.mockResolvedValue({ ...ART, content_hash: 'new-hash' });
    const { container } = render(<HtmlRenderer artifact={ART} />);
    await waitFor(() => expect(container.querySelector('iframe')).not.toBeNull());

    await fireBridgeEdit(container, {
      type: 'narra-edit-bridge:edit',
      innerBefore: 'Old Title',
      innerAfter: 'New Title',
      outerBefore: '<h1>Old Title</h1>',
    });

    await waitFor(() => expect(putContent).toHaveBeenCalledTimes(1));
    const [agentId, artifactId, body] = putContent.mock.calls[0];
    expect(agentId).toBe('agent_x');
    expect(artifactId).toBe('art_html01');
    expect(body.content).toContain('<h1>New Title</h1>');
    expect(body.base_hash).toBe(await sha256Hex(SOURCE));
  });

  it('an unanchorable edit degrades to the AI notice and never writes', async () => {
    const { container, getByText } = render(<HtmlRenderer artifact={ART} />);
    await waitFor(() => expect(container.querySelector('iframe')).not.toBeNull());

    await fireBridgeEdit(container, {
      type: 'narra-edit-bridge:edit',
      innerBefore: 'generated by javascript',
      innerAfter: 'changed',
      outerBefore: '<div>generated by javascript</div>',
    });

    await waitFor(() => {
      expect(getByText(/cannot be located/i)).toBeTruthy();
    });
    expect(putContent).not.toHaveBeenCalled();
  });

  it('ignores messages that are not from its own iframe', async () => {
    const { container } = render(<HtmlRenderer artifact={ART} />);
    await waitFor(() => expect(container.querySelector('iframe')).not.toBeNull());

    // Same effect flush as fireBridgeEdit: the `e.source` check must be what rejects
    // the message, not a stale mount-time listener that ignores everything.
    await act(async () => {});
    await act(async () => {
      window.dispatchEvent(
        new MessageEvent('message', {
          data: {
            type: 'narra-edit-bridge:edit',
            innerBefore: 'Old Title',
            innerAfter: 'evil',
            outerBefore: '<h1>Old Title</h1>',
          },
          source: window, // not the iframe
        }),
      );
    });
    await new Promise((r) => setTimeout(r, 20));
    expect(putContent).not.toHaveBeenCalled();
  });
});
