/**
 * @file_name: migrationImportQueue.ts
 * @author: NetMind.AI
 * @date: 2026-08-27
 * @description: Sequential scan→apply runner behind the one-page import list.
 * The backend is single-source per call (`/scan` extracts one source, `/apply`
 * writes one agent), so importing N checked rows is N sequential round-trips
 * driven from here — no backend change, and the user watches it row by row.
 *
 * Three rules the UI depends on:
 *   - one row failing NEVER stops the queue (a permission error on project #3
 *     must not lose projects #4-#9);
 *   - `shouldStop` is only consulted BETWEEN rows, never mid-write — aborting
 *     an in-flight `/apply` would leave a half-populated agent behind;
 *   - stopping does not mean waiting out the row that IS mid-write. Each apply
 *     carries an `importId`, and `hurry(importId)` tells the server to finish
 *     that row with deterministic (no-LLM) session summaries — seconds instead
 *     of one model call per session (Owner objection 2026-09-03: "don't make me
 *     wait for the current project"). Every session still lands; only the
 *     quality of the remaining summaries drops, and the result says how many.
 */

import type {
  MigrationApplyResult,
  MigrationFramework,
  StandardizedAgentImport,
} from '@/types';

export type ImportItemStatus =
  | 'queued'
  | 'scanning'
  | 'importing'
  | 'done'
  | 'failed'
  /** Never started: the user stopped the queue before this row's turn. */
  | 'skipped';

export interface ImportQueueItem {
  /** Row identity, echoed back on every progress event. */
  key: string;
  /** Per-apply handle the server accepts a "hurry up" for. Generated by the
   *  caller so the stop button can reach the row currently mid-write. */
  importId: string;
  path: string;
  framework: MigrationFramework;
  /** Display name for progress rows (the user never sees the raw path here). */
  label: string;
  /** Already-scanned payload (the row was expanded) — skips the scan step. */
  scanned?: StandardizedAgentImport | null;
  /** User edits (renamed agent, deselected sessions) applied before apply. */
  transform?: (scan: StandardizedAgentImport) => StandardizedAgentImport;
}

export interface ImportQueueProgress {
  key: string;
  label: string;
  status: ImportItemStatus;
  result?: MigrationApplyResult;
  error?: string;
}

export interface ImportQueueDeps {
  scan: (path: string, framework: MigrationFramework) => Promise<StandardizedAgentImport>;
  apply: (data: StandardizedAgentImport, importId: string) => Promise<MigrationApplyResult>;
  onProgress: (progress: ImportQueueProgress) => void;
  /** Checked before each row starts. True → the rest are reported `skipped`. */
  shouldStop?: () => boolean;
}

const message = (e: unknown): string => (e instanceof Error ? e.message : String(e));

/** Apply the row's inline edits to a scan result before it is POSTed to
 *  `/apply`: the (possibly renamed) agent plus only the sessions still checked.
 *  Passing `undefined` for sessions means "keep them all" — an untouched row
 *  must import everything, not nothing. */
export function applyImportEdits(
  scan: StandardizedAgentImport,
  name?: string,
  sessionIds?: ReadonlySet<string>,
): StandardizedAgentImport {
  return {
    ...scan,
    agent: { ...scan.agent, name: name?.trim() || scan.agent.name },
    sessions: sessionIds ? scan.sessions.filter((s) => sessionIds.has(s.session_id)) : scan.sessions,
  };
}

/**
 * Run every item through scan→apply, in order.
 *
 * Args:
 *   items: rows to import, in the order the user sees them
 *   deps: injected API calls + progress sink + stop predicate
 *
 * Returns:
 *   The final progress record of every item (same order as `items`).
 */
export async function runImportQueue(
  items: ImportQueueItem[],
  deps: ImportQueueDeps,
): Promise<ImportQueueProgress[]> {
  const final: ImportQueueProgress[] = [];
  let stopped = false;

  for (const item of items) {
    stopped = stopped || Boolean(deps.shouldStop?.());
    if (stopped) {
      const skipped: ImportQueueProgress = { key: item.key, label: item.label, status: 'skipped' };
      deps.onProgress(skipped);
      final.push(skipped);
      continue;
    }

    try {
      let scan = item.scanned ?? null;
      if (!scan) {
        deps.onProgress({ key: item.key, label: item.label, status: 'scanning' });
        scan = await deps.scan(item.path, item.framework);
      }
      deps.onProgress({ key: item.key, label: item.label, status: 'importing' });
      const payload = item.transform ? item.transform(scan) : scan;
      const result = await deps.apply(payload, item.importId);
      const done: ImportQueueProgress = {
        key: item.key,
        label: payload.agent.name || item.label,
        status: 'done',
        result,
      };
      deps.onProgress(done);
      final.push(done);
    } catch (e) {
      // Deliberately swallowed per item: the queue's contract is that one bad
      // source cannot cost the user the rest of the batch. The error is not
      // lost — it is surfaced on that row in the done summary, with a Retry.
      const failed: ImportQueueProgress = {
        key: item.key,
        label: item.label,
        status: 'failed',
        error: message(e),
      };
      deps.onProgress(failed);
      final.push(failed);
    }
  }

  return final;
}

/** Per-dimension totals across a finished batch — what the done summary shows. */
export function summarizeBatch(progress: ImportQueueProgress[]) {
  const done = progress.filter((p) => p.status === 'done' && p.result);
  const results = done.map((p) => p.result!);
  return {
    results,
    imported: results.length,
    failed: progress.filter((p) => p.status === 'failed').length,
    skipped: progress.filter((p) => p.status === 'skipped').length,
    narratives: results.reduce((n, r) => n + r.narratives_created.length, 0),
    memoryTurns: results.reduce((n, r) => n + r.memory_turns_retained, 0),
    skills: results.reduce(
      (n, r) => n + r.skills_copied.length + r.skills_installed.length,
      0,
    ),
    /** Sessions that landed with a deterministic summary because the user
     *  hurried the import. Shown in the done report — a thinner narrative is
     *  the user's own trade, but it must not be a silent one. */
    summariesDegraded: results.reduce((n, r) => n + (r.summaries_degraded ?? 0), 0),
  };
}
